PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE TABLE `users` (`id` text PRIMARY KEY NOT NULL,`name` text NOT NULL,`email` text NOT NULL,`avatar_url` text,`status` text DEFAULT 'active' NOT NULL,`created_at` text NOT NULL,`updated_at` text NOT NULL);--> statement-breakpoint
CREATE UNIQUE INDEX `users_email_unique` ON `users` (`email`);--> statement-breakpoint
CREATE TABLE `households` (`id` text PRIMARY KEY NOT NULL,`name` text NOT NULL,`created_by` text NOT NULL,`created_at` text NOT NULL,`updated_at` text NOT NULL,FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action);--> statement-breakpoint
CREATE TABLE `household_members` (`id` text PRIMARY KEY NOT NULL,`household_id` text NOT NULL,`user_id` text,`invited_email` text,`role` text DEFAULT 'member' NOT NULL,`status` text DEFAULT 'invited' NOT NULL,`joined_at` text,`created_at` text NOT NULL,FOREIGN KEY (`household_id`) REFERENCES `households`(`id`) ON UPDATE no action ON DELETE cascade,FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action);--> statement-breakpoint
CREATE INDEX `idx_household_members_household` ON `household_members` (`household_id`);--> statement-breakpoint
CREATE INDEX `idx_household_members_user` ON `household_members` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_household_members_invited_email` ON `household_members` (`invited_email`);--> statement-breakpoint
CREATE TABLE `accounts` (`id` text PRIMARY KEY NOT NULL,`household_id` text NOT NULL,`name` text NOT NULL,`type` text NOT NULL,`initial_balance_cents` integer DEFAULT 0 NOT NULL,`is_active` integer DEFAULT true NOT NULL,`created_at` text NOT NULL,`updated_at` text NOT NULL,FOREIGN KEY (`household_id`) REFERENCES `households`(`id`) ON UPDATE no action ON DELETE cascade);--> statement-breakpoint
CREATE INDEX `idx_accounts_household_active` ON `accounts` (`household_id`,`is_active`);--> statement-breakpoint
CREATE UNIQUE INDEX `accounts_household_name_unique` ON `accounts` (`household_id`,`name`);--> statement-breakpoint
CREATE TABLE `categories` (`id` text PRIMARY KEY NOT NULL,`household_id` text NOT NULL,`name` text NOT NULL,`type` text DEFAULT 'expense' NOT NULL,`color` text DEFAULT '#397f72' NOT NULL,`is_active` integer DEFAULT true NOT NULL,`created_at` text NOT NULL,`updated_at` text NOT NULL,FOREIGN KEY (`household_id`) REFERENCES `households`(`id`) ON UPDATE no action ON DELETE cascade);--> statement-breakpoint
CREATE INDEX `idx_categories_household_active` ON `categories` (`household_id`,`is_active`);--> statement-breakpoint
CREATE UNIQUE INDEX `categories_household_name_unique` ON `categories` (`household_id`,`name`);--> statement-breakpoint
CREATE TABLE `subcategories` (`id` text PRIMARY KEY NOT NULL,`household_id` text NOT NULL,`category_id` text NOT NULL,`name` text NOT NULL,`is_active` integer DEFAULT true NOT NULL,`created_at` text NOT NULL,`updated_at` text NOT NULL,FOREIGN KEY (`household_id`) REFERENCES `households`(`id`) ON UPDATE no action ON DELETE cascade,FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON UPDATE no action ON DELETE cascade);--> statement-breakpoint
CREATE INDEX `idx_subcategories_category` ON `subcategories` (`category_id`);--> statement-breakpoint
CREATE TABLE `transactions` (`id` text PRIMARY KEY NOT NULL,`household_id` text NOT NULL,`type` text NOT NULL,`amount_cents` integer NOT NULL CHECK (`amount_cents` > 0),`description` text NOT NULL,`category_id` text,`subcategory_id` text,`transaction_date` text NOT NULL,`transaction_time` text,`responsible_user_id` text NOT NULL,`account_id` text NOT NULL,`payment_method` text,`status` text DEFAULT 'confirmed' NOT NULL,`origin` text DEFAULT 'dashboard' NOT NULL,`notes` text,`created_at` text NOT NULL,`updated_at` text NOT NULL,FOREIGN KEY (`household_id`) REFERENCES `households`(`id`) ON UPDATE no action ON DELETE cascade,FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON UPDATE no action ON DELETE no action,FOREIGN KEY (`subcategory_id`) REFERENCES `subcategories`(`id`) ON UPDATE no action ON DELETE no action,FOREIGN KEY (`responsible_user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE no action);--> statement-breakpoint
CREATE INDEX `idx_transactions_household_date` ON `transactions` (`household_id`,`transaction_date`);--> statement-breakpoint
CREATE INDEX `idx_transactions_household_status` ON `transactions` (`household_id`,`status`);--> statement-breakpoint
CREATE INDEX `idx_transactions_account` ON `transactions` (`account_id`);--> statement-breakpoint
CREATE INDEX `idx_transactions_category` ON `transactions` (`category_id`);--> statement-breakpoint
CREATE INDEX `idx_transactions_responsible` ON `transactions` (`responsible_user_id`);--> statement-breakpoint
CREATE TABLE `audit_logs` (`id` text PRIMARY KEY NOT NULL,`household_id` text NOT NULL,`user_id` text NOT NULL,`action` text NOT NULL,`entity_type` text NOT NULL,`entity_id` text NOT NULL,`old_data` text,`new_data` text,`created_at` text NOT NULL,FOREIGN KEY (`household_id`) REFERENCES `households`(`id`) ON UPDATE no action ON DELETE cascade,FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action);--> statement-breakpoint
CREATE INDEX `idx_audit_logs_household_created` ON `audit_logs` (`household_id`,`created_at`);--> statement-breakpoint
PRAGMA optimize;
