CREATE UNIQUE INDEX `accounts_household_id_unique` ON `accounts` (`household_id`,`id`);
--> statement-breakpoint
CREATE UNIQUE INDEX `categories_household_id_unique` ON `categories` (`household_id`,`id`);
--> statement-breakpoint
CREATE UNIQUE INDEX `transactions_household_id_unique` ON `transactions` (`household_id`,`id`);
--> statement-breakpoint
CREATE UNIQUE INDEX `household_members_household_user_unique` ON `household_members` (`household_id`,`user_id`);
--> statement-breakpoint
CREATE TRIGGER `transactions_household_relations_insert` BEFORE INSERT ON `transactions` FOR EACH ROW WHEN NOT EXISTS (SELECT 1 FROM `accounts` WHERE `id` = NEW.`account_id` AND `household_id` = NEW.`household_id`) OR (NEW.`category_id` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `categories` WHERE `id` = NEW.`category_id` AND `household_id` = NEW.`household_id`)) OR (NEW.`subcategory_id` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `subcategories` WHERE `id` = NEW.`subcategory_id` AND `household_id` = NEW.`household_id` AND NEW.`category_id` IS NOT NULL AND `category_id` = NEW.`category_id`)) BEGIN SELECT RAISE(ABORT, 'transaction relation belongs to another household'); END;
--> statement-breakpoint
CREATE TRIGGER `transactions_household_relations_update` BEFORE UPDATE OF `household_id`,`account_id`,`category_id`,`subcategory_id` ON `transactions` FOR EACH ROW WHEN NOT EXISTS (SELECT 1 FROM `accounts` WHERE `id` = NEW.`account_id` AND `household_id` = NEW.`household_id`) OR (NEW.`category_id` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `categories` WHERE `id` = NEW.`category_id` AND `household_id` = NEW.`household_id`)) OR (NEW.`subcategory_id` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `subcategories` WHERE `id` = NEW.`subcategory_id` AND `household_id` = NEW.`household_id` AND NEW.`category_id` IS NOT NULL AND `category_id` = NEW.`category_id`)) BEGIN SELECT RAISE(ABORT, 'transaction relation belongs to another household'); END;
--> statement-breakpoint
CREATE TABLE `credit_cards` (`id` text PRIMARY KEY NOT NULL,`household_id` text NOT NULL,`name` text NOT NULL,`institution` text NOT NULL,`holder` text NOT NULL,`limit_cents` integer NOT NULL CHECK (`limit_cents` >= 0),`closing_day` integer NOT NULL CHECK (`closing_day` BETWEEN 1 AND 31),`due_day` integer NOT NULL CHECK (`due_day` BETWEEN 1 AND 31),`is_active` integer DEFAULT 1 NOT NULL CHECK (`is_active` IN (0,1)),`notes` text,`created_at` text NOT NULL,`updated_at` text NOT NULL,UNIQUE (`household_id`,`id`),FOREIGN KEY (`household_id`) REFERENCES `households`(`id`) ON DELETE cascade);
--> statement-breakpoint
CREATE UNIQUE INDEX `credit_cards_household_name_unique` ON `credit_cards` (`household_id`,`name`); CREATE INDEX `idx_credit_cards_household_active` ON `credit_cards` (`household_id`,`is_active`);
--> statement-breakpoint
CREATE TABLE `card_purchases` (`id` text PRIMARY KEY NOT NULL,`household_id` text NOT NULL,`card_id` text NOT NULL,`description` text NOT NULL,`total_cents` integer NOT NULL CHECK (`total_cents` > 0),`purchase_date` text NOT NULL,`installment_count` integer DEFAULT 1 NOT NULL CHECK (`installment_count` BETWEEN 1 AND 120),`category_id` text,`notes` text,`status` text DEFAULT 'active' NOT NULL CHECK (`status` IN ('active','cancelled')),`created_by_user_id` text NOT NULL,`origin` text DEFAULT 'web' NOT NULL CHECK (`origin` IN ('web','telegram','system')),`created_at` text NOT NULL,`updated_at` text NOT NULL,UNIQUE (`household_id`,`id`),FOREIGN KEY (`household_id`) REFERENCES `households`(`id`) ON DELETE cascade,FOREIGN KEY (`household_id`,`card_id`) REFERENCES `credit_cards`(`household_id`,`id`),FOREIGN KEY (`household_id`,`category_id`) REFERENCES `categories`(`household_id`,`id`),FOREIGN KEY (`household_id`,`created_by_user_id`) REFERENCES `household_members`(`household_id`,`user_id`));
--> statement-breakpoint
CREATE INDEX `idx_card_purchases_household_date` ON `card_purchases` (`household_id`,`purchase_date`); CREATE INDEX `idx_card_purchases_card` ON `card_purchases` (`card_id`);
--> statement-breakpoint
CREATE TABLE `card_invoices` (`id` text PRIMARY KEY NOT NULL,`household_id` text NOT NULL,`card_id` text NOT NULL,`reference_month` text NOT NULL,`due_date` text NOT NULL,`status` text DEFAULT 'open' NOT NULL CHECK (`status` IN ('open','closed','paid')),`paid_at` text,`created_at` text NOT NULL,`updated_at` text NOT NULL,UNIQUE (`household_id`,`id`),FOREIGN KEY (`household_id`) REFERENCES `households`(`id`) ON DELETE cascade,FOREIGN KEY (`household_id`,`card_id`) REFERENCES `credit_cards`(`household_id`,`id`));
--> statement-breakpoint
CREATE UNIQUE INDEX `card_invoices_card_month_unique` ON `card_invoices` (`household_id`,`card_id`,`reference_month`); CREATE INDEX `idx_card_invoices_household_due` ON `card_invoices` (`household_id`,`due_date`);
--> statement-breakpoint
CREATE TABLE `card_installments` (`id` text PRIMARY KEY NOT NULL,`household_id` text NOT NULL,`purchase_id` text NOT NULL,`invoice_id` text NOT NULL,`installment_number` integer NOT NULL,`installment_count` integer NOT NULL CHECK (`installment_count` BETWEEN 1 AND 120),`amount_cents` integer NOT NULL CHECK (`amount_cents` > 0),`status` text DEFAULT 'pending' NOT NULL CHECK (`status` IN ('pending','paid','cancelled')),`created_at` text NOT NULL,`updated_at` text NOT NULL,CHECK (`installment_number` BETWEEN 1 AND `installment_count`),FOREIGN KEY (`household_id`) REFERENCES `households`(`id`) ON DELETE cascade,FOREIGN KEY (`household_id`,`purchase_id`) REFERENCES `card_purchases`(`household_id`,`id`) ON DELETE cascade,FOREIGN KEY (`household_id`,`invoice_id`) REFERENCES `card_invoices`(`household_id`,`id`));
--> statement-breakpoint
CREATE UNIQUE INDEX `card_installments_purchase_number_unique` ON `card_installments` (`purchase_id`,`installment_number`); CREATE INDEX `idx_card_installments_household_invoice` ON `card_installments` (`household_id`,`invoice_id`);
--> statement-breakpoint
CREATE TABLE `invoice_payments` (`id` text PRIMARY KEY NOT NULL,`household_id` text NOT NULL,`invoice_id` text NOT NULL,`account_id` text NOT NULL,`amount_cents` integer NOT NULL CHECK (`amount_cents` > 0),`paid_at` text NOT NULL,`created_by_user_id` text NOT NULL,`created_at` text NOT NULL,FOREIGN KEY (`household_id`) REFERENCES `households`(`id`) ON DELETE cascade,FOREIGN KEY (`household_id`,`invoice_id`) REFERENCES `card_invoices`(`household_id`,`id`),FOREIGN KEY (`household_id`,`account_id`) REFERENCES `accounts`(`household_id`,`id`),FOREIGN KEY (`household_id`,`created_by_user_id`) REFERENCES `household_members`(`household_id`,`user_id`));
--> statement-breakpoint
CREATE UNIQUE INDEX `invoice_payments_invoice_unique` ON `invoice_payments` (`invoice_id`); CREATE INDEX `idx_invoice_payments_household_account` ON `invoice_payments` (`household_id`,`account_id`);
--> statement-breakpoint
CREATE TABLE `recurring_bill_series` (`id` text PRIMARY KEY NOT NULL,`household_id` text NOT NULL,`description` text NOT NULL,`amount_cents` integer NOT NULL CHECK (`amount_cents` > 0),`category_id` text,`account_id` text,`day_of_month` integer NOT NULL CHECK (`day_of_month` BETWEEN 1 AND 31),`starts_on` text NOT NULL,`ends_on` text CHECK (`ends_on` IS NULL OR `ends_on` >= `starts_on`),`is_active` integer DEFAULT 1 NOT NULL CHECK (`is_active` IN (0,1)),`notes` text,`created_by_user_id` text NOT NULL,`origin` text DEFAULT 'web' NOT NULL CHECK (`origin` IN ('web','telegram','system')),`created_at` text NOT NULL,`updated_at` text NOT NULL,UNIQUE (`household_id`,`id`),FOREIGN KEY (`household_id`) REFERENCES `households`(`id`) ON DELETE cascade,FOREIGN KEY (`household_id`,`category_id`) REFERENCES `categories`(`household_id`,`id`),FOREIGN KEY (`household_id`,`account_id`) REFERENCES `accounts`(`household_id`,`id`),FOREIGN KEY (`household_id`,`created_by_user_id`) REFERENCES `household_members`(`household_id`,`user_id`));
--> statement-breakpoint
CREATE INDEX `idx_recurring_bill_series_household_active` ON `recurring_bill_series` (`household_id`,`is_active`);
--> statement-breakpoint
CREATE TABLE `bills` (`id` text PRIMARY KEY NOT NULL,`household_id` text NOT NULL,`description` text NOT NULL,`amount_cents` integer NOT NULL CHECK (`amount_cents` > 0),`category_id` text,`due_date` text NOT NULL,`account_id` text,`recurrence` text DEFAULT 'none' NOT NULL CHECK (`recurrence` IN ('none','monthly')),`recurrence_series_id` text,`recurrence_end_date` text,`notes` text,`status` text DEFAULT 'pending' NOT NULL CHECK (`status` IN ('pending','paid','cancelled')),`paid_at` text,`payment_transaction_id` text,`created_by_user_id` text NOT NULL,`origin` text DEFAULT 'web' NOT NULL CHECK (`origin` IN ('web','telegram','system')),`created_at` text NOT NULL,`updated_at` text NOT NULL,CHECK ((`recurrence` = 'none' AND `recurrence_series_id` IS NULL AND `recurrence_end_date` IS NULL) OR (`recurrence` = 'monthly' AND `recurrence_series_id` IS NOT NULL)),FOREIGN KEY (`household_id`) REFERENCES `households`(`id`) ON DELETE cascade,FOREIGN KEY (`household_id`,`category_id`) REFERENCES `categories`(`household_id`,`id`),FOREIGN KEY (`household_id`,`account_id`) REFERENCES `accounts`(`household_id`,`id`),FOREIGN KEY (`household_id`,`recurrence_series_id`) REFERENCES `recurring_bill_series`(`household_id`,`id`),FOREIGN KEY (`household_id`,`payment_transaction_id`) REFERENCES `transactions`(`household_id`,`id`),FOREIGN KEY (`household_id`,`created_by_user_id`) REFERENCES `household_members`(`household_id`,`user_id`));
--> statement-breakpoint
CREATE UNIQUE INDEX `bills_series_due_unique` ON `bills` (`recurrence_series_id`,`due_date`); CREATE INDEX `idx_bills_household_due_status` ON `bills` (`household_id`,`due_date`,`status`); CREATE INDEX `idx_bills_recurrence_series` ON `bills` (`recurrence_series_id`);
--> statement-breakpoint
CREATE TABLE `notification_preferences` (`household_id` text PRIMARY KEY NOT NULL,`enabled` integer DEFAULT 1 NOT NULL CHECK (`enabled` IN (0,1)),`offsets_json` text DEFAULT '[7,3,1,0,-1]' NOT NULL,`updated_at` text NOT NULL,FOREIGN KEY (`household_id`) REFERENCES `households`(`id`) ON DELETE cascade);
--> statement-breakpoint
CREATE TABLE `notification_log` (`id` text PRIMARY KEY NOT NULL,`household_id` text NOT NULL,`entity_type` text NOT NULL,`entity_id` text NOT NULL,`event_key` text NOT NULL,`channel` text NOT NULL,`recipient_key` text NOT NULL,`sent_at` text NOT NULL,FOREIGN KEY (`household_id`) REFERENCES `households`(`id`) ON DELETE cascade);
--> statement-breakpoint
CREATE UNIQUE INDEX `notification_log_idempotency_unique` ON `notification_log` (`household_id`,`entity_type`,`entity_id`,`event_key`,`channel`,`recipient_key`); CREATE INDEX `idx_notification_log_household_sent` ON `notification_log` (`household_id`,`sent_at`);
--> statement-breakpoint
CREATE TABLE `telegram_links` (`id` text PRIMARY KEY NOT NULL,`household_id` text NOT NULL,`user_id` text NOT NULL,`telegram_user_id` text NOT NULL,`chat_id` text NOT NULL,`is_active` integer DEFAULT 1 NOT NULL CHECK (`is_active` IN (0,1)),`linked_at` text NOT NULL,`updated_at` text NOT NULL,FOREIGN KEY (`household_id`) REFERENCES `households`(`id`) ON DELETE cascade,FOREIGN KEY (`household_id`,`user_id`) REFERENCES `household_members`(`household_id`,`user_id`));
--> statement-breakpoint
CREATE UNIQUE INDEX `telegram_links_user_unique` ON `telegram_links` (`telegram_user_id`); CREATE INDEX `idx_telegram_links_household_active` ON `telegram_links` (`household_id`,`is_active`);
--> statement-breakpoint
CREATE TABLE `telegram_link_codes` (`id` text PRIMARY KEY NOT NULL,`household_id` text NOT NULL,`user_id` text NOT NULL,`code_hash` text NOT NULL,`expires_at` text NOT NULL,`used_at` text,`created_at` text NOT NULL,FOREIGN KEY (`household_id`) REFERENCES `households`(`id`) ON DELETE cascade,FOREIGN KEY (`household_id`,`user_id`) REFERENCES `household_members`(`household_id`,`user_id`));
--> statement-breakpoint
CREATE UNIQUE INDEX `telegram_link_codes_hash_unique` ON `telegram_link_codes` (`code_hash`); CREATE INDEX `idx_telegram_link_codes_expiry` ON `telegram_link_codes` (`expires_at`);
--> statement-breakpoint
CREATE TABLE `telegram_conversation_states` (`telegram_user_id` text PRIMARY KEY NOT NULL,`household_id` text NOT NULL,`payload_json` text NOT NULL,`expires_at` text NOT NULL,`updated_at` text NOT NULL,FOREIGN KEY (`household_id`) REFERENCES `households`(`id`) ON DELETE cascade);
--> statement-breakpoint
CREATE TABLE `telegram_processed_updates` (`update_id` text PRIMARY KEY NOT NULL,`received_at` text NOT NULL);
--> statement-breakpoint
PRAGMA optimize;
