import { env } from "cloudflare:workers";
import { NextResponse } from "next/server";
import { and, desc, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { accounts, bills, cardInstallments, cardInvoices, cardPurchases, categories, creditCards, invoicePayments, telegramConversationStates, telegramLinkCodes, telegramLinks, telegramProcessedUpdates, transactions } from "@/db/schema";
import { digestToken, hmacToken } from "@/lib/auth-crypto.mjs";
import { addMonths, buildInstallmentPlan, parseTelegramMessage, simulatePurchase } from "@/lib/finance-rules.mjs";
import { clearRateLimit, consumeRateLimit, RateLimitError } from "@/lib/rate-limit";
import { formatBrl, sendTelegramMessage } from "@/lib/telegram";

export const dynamic = "force-dynamic";
type Update = { update_id: number; message?: { text?: string; chat: { id: number }; from?: { id: number } } };
type ParsedMessage = { intent: string; code?: string; query?: string; period?: string; missing?: string[]; type?: "income" | "expense"; amountCents?: number; description?: string; installmentCount?: number; cardId?: string | null; categoryId?: string | null; accountId?: string | null };
const uid = (prefix: string) => `${prefix}_${crypto.randomUUID()}`;

export async function POST(request: Request) {
  if (!env.TELEGRAM_WEBHOOK_SECRET || request.headers.get("x-telegram-bot-api-secret-token") !== env.TELEGRAM_WEBHOOK_SECRET) return NextResponse.json({ error: "Webhook não autorizado." }, { status: 401 });
  const update = await request.json() as Update; const updateId = String(update.update_id); const db = getDb();
  const [processed] = await db.select().from(telegramProcessedUpdates).where(eq(telegramProcessedUpdates.updateId, updateId)).limit(1); if (processed) return NextResponse.json({ ok: true, duplicate: true });
  try { await db.insert(telegramProcessedUpdates).values({ updateId, receivedAt: new Date().toISOString() }); } catch { return NextResponse.json({ ok: true, duplicate: true }); }
  const telegramUserId = String(update.message?.from?.id ?? ""); const chatId = String(update.message?.chat.id ?? ""); const text = update.message?.text?.trim() ?? "";
  if (!telegramUserId || !chatId || !text) return NextResponse.json({ ok: true });
  try {
    if (/^\/conectar\s+\d{6}$/i.test(text)) {
      const attemptKey = `telegram-code-connect:${await digestToken(telegramUserId)}`;
      try { await consumeRateLimit(attemptKey, 5, 10 * 60_000, 15 * 60_000); } catch (error) { if (error instanceof RateLimitError) { await sendTelegramMessage(chatId, "Muitas tentativas. Aguarde 15 minutos antes de tentar novamente."); return NextResponse.json({ ok: true }); } throw error; }
      if (!env.TELEGRAM_LINK_CODE_SECRET || !env.DB) { await sendTelegramMessage(chatId, "A vinculação está temporariamente indisponível."); return NextResponse.json({ ok: true }); }
      const code = text.match(/\d{6}/)![0]; const [record] = await db.select().from(telegramLinkCodes).where(eq(telegramLinkCodes.codeHash, await hmacToken(code, env.TELEGRAM_LINK_CODE_SECRET))).limit(1);
      if (!record || record.usedAt || record.expiresAt <= new Date().toISOString()) { await sendTelegramMessage(chatId, "Código inválido, expirado ou já utilizado."); return NextResponse.json({ ok: true }); }
      const [other] = await db.select().from(telegramLinks).where(eq(telegramLinks.telegramUserId, telegramUserId)).limit(1); if (other && other.householdId !== record.householdId) { await sendTelegramMessage(chatId, "Esta conta Telegram já está vinculada a outra família."); return NextResponse.json({ ok: true }); }
      const timestamp = new Date().toISOString();
      const consumed = await env.DB.prepare("UPDATE telegram_link_codes SET used_at = ? WHERE id = ? AND used_at IS NULL AND expires_at > ?").bind(timestamp, record.id, timestamp).run();
      if ((consumed.meta.changes ?? 0) !== 1) { await sendTelegramMessage(chatId, "Código inválido, expirado ou já utilizado."); return NextResponse.json({ ok: true }); }
      if (other) await db.update(telegramLinks).set({ userId: record.userId, householdId: record.householdId, chatId, isActive: true, updatedAt: timestamp }).where(and(eq(telegramLinks.id, other.id), eq(telegramLinks.householdId, record.householdId))); else await db.insert(telegramLinks).values({ id: uid("telegram_link"), householdId: record.householdId, userId: record.userId, telegramUserId, chatId, isActive: true, linkedAt: timestamp, updatedAt: timestamp });
      await clearRateLimit(attemptKey); await sendTelegramMessage(chatId, "✅ Telegram conectado com segurança à sua família."); return NextResponse.json({ ok: true });
    }
    const [link] = await db.select().from(telegramLinks).where(and(eq(telegramLinks.telegramUserId, telegramUserId), eq(telegramLinks.isActive, true))).limit(1); if (!link) { await sendTelegramMessage(chatId, "Seu Telegram ainda não está conectado. Gere um código em Configurações > Telegram no site."); return NextResponse.json({ ok: true }); }
    const [pendingState] = await db.select().from(telegramConversationStates).where(and(eq(telegramConversationStates.telegramUserId, telegramUserId), eq(telegramConversationStates.householdId, link.householdId))).limit(1);
    if (pendingState && /^cancelar$/i.test(text)) { await db.delete(telegramConversationStates).where(eq(telegramConversationStates.telegramUserId, telegramUserId)); await sendTelegramMessage(chatId, "Operação cancelada."); return NextResponse.json({ ok: true }); }
    if (pendingState && pendingState.expiresAt <= new Date().toISOString()) await db.delete(telegramConversationStates).where(eq(telegramConversationStates.telegramUserId, telegramUserId));
    else if (pendingState) {
      const saved = JSON.parse(pendingState.payloadJson) as ParsedMessage; const accountRows = await db.select().from(accounts).where(and(eq(accounts.householdId, link.householdId), eq(accounts.isActive, true))); const selectedAccount = accountRows.find((account) => account.name.toLocaleLowerCase("pt-BR") === text.toLocaleLowerCase("pt-BR"));
      if (selectedAccount && saved.type && saved.amountCents && saved.description) { const timestamp = new Date().toISOString(); await db.insert(transactions).values({ id: uid("transaction"), householdId: link.householdId, type: saved.type, amountCents: saved.amountCents, description: saved.description, transactionDate: timestamp.slice(0, 10), responsibleUserId: link.userId, accountId: selectedAccount.id, status: "confirmed", origin: "telegram", createdAt: timestamp, updatedAt: timestamp }); await db.delete(telegramConversationStates).where(eq(telegramConversationStates.telegramUserId, telegramUserId)); await sendTelegramMessage(chatId, `✅ ${saved.type === "income" ? "Receita" : "Despesa"} registrada\n\n${saved.description}\n${formatBrl(saved.amountCents)}\nConta: ${selectedAccount.name}`); return NextResponse.json({ ok: true }); }
      await sendTelegramMessage(chatId, `Não encontrei essa conta. Escolha uma destas:\n${accountRows.map((account) => `• ${account.name}`).join("\n")}\n\nOu envie “Cancelar”.`); return NextResponse.json({ ok: true });
    }
    const cardRows = await db.select().from(creditCards).where(and(eq(creditCards.householdId, link.householdId), eq(creditCards.isActive, true))); const knownAccounts = await db.select().from(accounts).where(and(eq(accounts.householdId, link.householdId), eq(accounts.isActive, true))); const categoryRows = await db.select().from(categories).where(and(eq(categories.householdId, link.householdId), eq(categories.isActive, true))); const parsed = parseTelegramMessage(text, { cards: cardRows, accounts: knownAccounts, categories: categoryRows }) as ParsedMessage;
    if (parsed.intent === "cancel") { await db.delete(telegramConversationStates).where(eq(telegramConversationStates.telegramUserId, telegramUserId)); await sendTelegramMessage(chatId, "Operação cancelada."); return NextResponse.json({ ok: true }); }
    if (parsed.intent === "undo_last") { const [last] = await db.select().from(transactions).where(and(eq(transactions.householdId, link.householdId), eq(transactions.responsibleUserId, link.userId), eq(transactions.origin, "telegram"))).orderBy(desc(transactions.createdAt)).limit(1); if (!last) await sendTelegramMessage(chatId, "Não encontrei lançamento do Telegram para desfazer."); else { await db.delete(transactions).where(and(eq(transactions.id, last.id), eq(transactions.householdId, link.householdId))); await sendTelegramMessage(chatId, `↩️ Lançamento desfeito: ${last.description} · ${formatBrl(last.amountCents)}`); } return NextResponse.json({ ok: true }); }
    if (parsed.intent === "query") { await handleQuery(db, link, parsed.query ?? "unknown", parsed.period ?? "month", chatId, parsed.cardId); return NextResponse.json({ ok: true }); }
    if ((parsed.intent === "transaction" || parsed.intent === "simulate") && parsed.missing?.length) { const expiresAt = new Date(Date.now() + 10 * 60_000).toISOString(); await db.insert(telegramConversationStates).values({ telegramUserId, householdId: link.householdId, payloadJson: JSON.stringify(parsed), expiresAt, updatedAt: new Date().toISOString() }).onConflictDoUpdate({ target: telegramConversationStates.telegramUserId, set: { payloadJson: JSON.stringify(parsed), expiresAt, updatedAt: new Date().toISOString() } }); await sendTelegramMessage(chatId, `Preciso de mais uma informação: ${parsed.missing.join(", ")}. Envie “Cancelar” para interromper.`); return NextResponse.json({ ok: true }); }
    if (parsed.intent === "simulate") { await handleSimulation(db, link, parsed, cardRows, chatId); return NextResponse.json({ ok: true }); }
    if (parsed.intent === "transaction") {
      if (parsed.cardId) { const card = cardRows.find((item) => item.id === parsed.cardId)!; const timestamp = new Date().toISOString(); const purchaseId = uid("purchase"); const amountCents = parsed.amountCents!; const installmentCount = parsed.installmentCount!; const description = parsed.description!; const plan = buildInstallmentPlan({ totalCents: amountCents, count: installmentCount, purchaseDate: timestamp.slice(0, 10), closingDay: card.closingDay, dueDay: card.dueDay }); await db.insert(cardPurchases).values({ id: purchaseId, householdId: link.householdId, cardId: card.id, description, totalCents: amountCents, purchaseDate: timestamp.slice(0, 10), installmentCount, categoryId: parsed.categoryId, status: "active", createdByUserId: link.userId, origin: "telegram", createdAt: timestamp, updatedAt: timestamp }); for (const part of plan) { let [invoice] = await db.select().from(cardInvoices).where(and(eq(cardInvoices.householdId, link.householdId), eq(cardInvoices.cardId, card.id), eq(cardInvoices.referenceMonth, part.referenceMonth))).limit(1); if (!invoice) { invoice = { id: uid("invoice"), householdId: link.householdId, cardId: card.id, referenceMonth: part.referenceMonth, dueDate: part.dueDate, status: "open", paidAt: null, createdAt: timestamp, updatedAt: timestamp }; await db.insert(cardInvoices).values(invoice); } await db.insert(cardInstallments).values({ id: uid("installment"), householdId: link.householdId, purchaseId, invoiceId: invoice.id, installmentNumber: part.installmentNumber, installmentCount: part.installmentCount, amountCents: part.amountCents, status: "pending", createdAt: timestamp, updatedAt: timestamp }); } await sendTelegramMessage(chatId, `✅ Compra registrada\n\n${description}\nTotal: ${formatBrl(amountCents)}\n${card.name}\n${installmentCount}x · primeira parcela ${plan[0].referenceMonth}`); return NextResponse.json({ ok: true }); }
      const accountRows = knownAccounts; if (!accountRows.length) { await sendTelegramMessage(chatId, "Cadastre uma conta no site antes do primeiro lançamento."); return NextResponse.json({ ok: true }); } if (!parsed.accountId && accountRows.length > 1) { const expiresAt = new Date(Date.now() + 10 * 60_000).toISOString(); await db.insert(telegramConversationStates).values({ telegramUserId, householdId: link.householdId, payloadJson: JSON.stringify(parsed), expiresAt, updatedAt: new Date().toISOString() }).onConflictDoUpdate({ target: telegramConversationStates.telegramUserId, set: { payloadJson: JSON.stringify(parsed), expiresAt, updatedAt: new Date().toISOString() } }); await sendTelegramMessage(chatId, `Em qual conta deseja registrar?\n${accountRows.map((item) => `• ${item.name}`).join("\n")}\n\nEnvie o nome da conta ou “Cancelar”.`); return NextResponse.json({ ok: true }); }
      const chosenAccount = accountRows.find((account) => account.id === parsed.accountId) ?? accountRows[0]; const timestamp = new Date().toISOString(); const type = parsed.type!; const amountCents = parsed.amountCents!; const description = parsed.description!; await db.insert(transactions).values({ id: uid("transaction"), householdId: link.householdId, type, amountCents, description, categoryId: parsed.categoryId, transactionDate: timestamp.slice(0, 10), responsibleUserId: link.userId, accountId: chosenAccount.id, status: "confirmed", origin: "telegram", createdAt: timestamp, updatedAt: timestamp }); await sendTelegramMessage(chatId, `✅ ${type === "income" ? "Receita" : "Despesa"} registrada\n\n${description}\n${formatBrl(amountCents)}\nConta: ${chosenAccount.name}`); return NextResponse.json({ ok: true });
    }
    await sendTelegramMessage(chatId, "Não entendi com segurança. Informe tipo, valor e descrição, por exemplo: “gastei 100 de gasolina”."); return NextResponse.json({ ok: true });
  } catch (error) { console.error("telegram_webhook_failed", error); return NextResponse.json({ ok: true }); }
}

async function handleQuery(db: ReturnType<typeof getDb>, link: typeof telegramLinks.$inferSelect, query: string, period: string, chatId: string, cardId?: string | null) {
  const today = new Date().toISOString().slice(0, 10); const month = today.slice(0, 7);
  if (query === "balance") { const accountRows = await db.select().from(accounts).where(and(eq(accounts.householdId, link.householdId), eq(accounts.isActive, true))); const rows = await db.select().from(transactions).where(eq(transactions.householdId, link.householdId)); const payments = await db.select().from(invoicePayments).where(eq(invoicePayments.householdId, link.householdId)); const balance = accountRows.reduce((sum, account) => sum + account.initialBalanceCents + rows.filter((item) => item.accountId === account.id && item.status === "confirmed").reduce((value, item) => value + (item.type === "income" ? item.amountCents : -item.amountCents), 0) - payments.filter((item) => item.accountId === account.id).reduce((value, item) => value + item.amountCents, 0), 0); await sendTelegramMessage(chatId, `Saldo disponível da família: ${formatBrl(balance)}`); return; }
  if (query === "income_month" || query === "expenses") { const rows = await db.select().from(transactions).where(eq(transactions.householdId, link.householdId)); const type = query === "income_month" ? "income" : "expense"; const weekStart = new Date(Date.now() - 6 * 86400000).toISOString().slice(0, 10); const total = rows.filter((item) => item.status === "confirmed" && item.type === type && (period === "week" ? item.transactionDate >= weekStart && item.transactionDate <= today : item.transactionDate.startsWith(month))).reduce((sum, item) => sum + item.amountCents, 0); await sendTelegramMessage(chatId, `${type === "income" ? "Entradas" : "Despesas"} ${period === "week" ? "nos últimos 7 dias" : "no mês"}: ${formatBrl(total)}`); return; }
  if (query === "bills") { const rows = await db.select().from(bills).where(and(eq(bills.householdId, link.householdId), eq(bills.status, "pending"))); const end = period === "tomorrow" ? new Date(Date.now() + 86400000).toISOString().slice(0, 10) : period === "week" ? new Date(Date.now() + 7 * 86400000).toISOString().slice(0, 10) : `${month}-31`; const start = period === "tomorrow" ? end : today; const visible = rows.filter((item) => item.dueDate >= start && item.dueDate <= end); await sendTelegramMessage(chatId, visible.length ? `📅 Contas no período\n\n${visible.map((item) => `${item.description}: ${formatBrl(item.amountCents)} · ${item.dueDate}`).join("\n")}\n\nTotal: ${formatBrl(visible.reduce((sum, item) => sum + item.amountCents, 0))}` : "Nenhuma conta pendente nesse período."); return; }
  if (query === "invoices" || query === "installments") { const targetMonth = period === "next_month" ? nextMonth(month) : month; const invoiceRows = await db.select().from(cardInvoices).where(eq(cardInvoices.householdId, link.householdId)); const visibleInvoices = invoiceRows.filter((invoice) => invoice.referenceMonth === targetMonth && (!cardId || invoice.cardId === cardId)); const parts = await db.select().from(cardInstallments).where(eq(cardInstallments.householdId, link.householdId)); const visible = parts.filter((part) => visibleInvoices.some((invoice) => invoice.id === part.invoiceId) && part.status !== "cancelled"); if (query === "invoices") { const total = visible.reduce((sum, part) => sum + part.amountCents, 0); await sendTelegramMessage(chatId, `💳 Faturas de ${targetMonth}: ${formatBrl(total)} (${visible.length} parcela(s)).`); } else await sendTelegramMessage(chatId, visible.length ? `Parcelas de ${targetMonth}:\n${visible.map((part) => `${part.installmentNumber}/${part.installmentCount} · ${formatBrl(part.amountCents)}`).join("\n")}` : "Nenhuma parcela nesse mês."); return; }
  await sendTelegramMessage(chatId, "A consulta está disponível no painel mensal do sistema.");
}

function nextMonth(month: string) { const [year, value] = month.split("-").map(Number); const date = new Date(Date.UTC(year, value, 1)); return `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, "0")}`; }

async function handleSimulation(db: ReturnType<typeof getDb>, link: typeof telegramLinks.$inferSelect, parsed: ParsedMessage, cardRows: Array<typeof creditCards.$inferSelect>, chatId: string) {
  const today = new Date().toISOString().slice(0, 10); const currentMonth = today.slice(0, 7); const accountRows = await db.select().from(accounts).where(eq(accounts.householdId, link.householdId)); const transactionRows = await db.select().from(transactions).where(eq(transactions.householdId, link.householdId)); const paymentRows = await db.select().from(invoicePayments).where(eq(invoicePayments.householdId, link.householdId)); const billRows = await db.select().from(bills).where(eq(bills.householdId, link.householdId)); const invoiceRows = await db.select().from(cardInvoices).where(eq(cardInvoices.householdId, link.householdId)); const installmentRows = await db.select().from(cardInstallments).where(eq(cardInstallments.householdId, link.householdId));
  const balances = new Map(accountRows.map((account) => [account.id, account.initialBalanceCents])); for (const item of transactionRows) if (item.status === "confirmed" && item.transactionDate <= today) balances.set(item.accountId, (balances.get(item.accountId) ?? 0) + (item.type === "income" ? item.amountCents : -item.amountCents)); for (const payment of paymentRows) if (payment.paidAt <= today) balances.set(payment.accountId, (balances.get(payment.accountId) ?? 0) - payment.amountCents); const availableCents = accountRows.filter((account) => account.isActive).reduce((sum, account) => sum + (balances.get(account.id) ?? 0), 0);
  let firstImpactMonth = currentMonth; if (parsed.cardId) { const card = cardRows.find((item) => item.id === parsed.cardId); if (card) firstImpactMonth = buildInstallmentPlan({ totalCents: parsed.amountCents!, count: parsed.installmentCount!, purchaseDate: today, closingDay: card.closingDay, dueDay: card.dueDay })[0].referenceMonth; }
  const invoiceById = new Map(invoiceRows.map((invoice) => [invoice.id, invoice])); const horizon = Math.max(12, parsed.installmentCount ?? 1); const months = Array.from({ length: horizon }, (_, index) => addMonths(currentMonth, index)).map((month) => { const future = transactionRows.filter((item) => item.status === "confirmed" && item.transactionDate > today && item.transactionDate.startsWith(month)); return { month, incomeCents: future.filter((item) => item.type === "income").reduce((sum, item) => sum + item.amountCents, 0), commitmentCents: future.filter((item) => item.type === "expense").reduce((sum, item) => sum + item.amountCents, 0) + billRows.filter((item) => item.status === "pending" && item.dueDate.startsWith(month)).reduce((sum, item) => sum + item.amountCents, 0) + installmentRows.filter((item) => item.status === "pending" && invoiceById.get(item.invoiceId)?.referenceMonth === month).reduce((sum, item) => sum + item.amountCents, 0) }; });
  const result = simulatePurchase({ startMonth: currentMonth, availableCents, purchaseCents: parsed.amountCents!, installmentCount: parsed.installmentCount ?? 1, firstImpactMonth, months }); const icon = result.rating === "green" ? "🟢" : result.rating === "yellow" ? "🟡" : result.rating === "red" ? "🔴" : "⚪"; const title = result.label ?? "Não existem informações suficientes para uma análise confiável."; await sendTelegramMessage(chatId, `${icon} ${title.toLocaleUpperCase("pt-BR")}\n\nCompra: ${parsed.description}\nValor: ${formatBrl(parsed.amountCents!)}\n${parsed.installmentCount ?? 1}x de aproximadamente ${formatBrl(result.installmentCents ?? parsed.amountCents!)}\n\n${result.reasons.join("\n")}\n\nNenhum lançamento foi criado.`);
}
